### ISSUE TITLE
Block Events and Behaviors Notification

### ISSUE THREAD

**Issue by ci010** [UnknownDomainGames/PanguEngine#33]
- [x] Click 

当方块被鼠标左键点击时trigger。

Event Fields:  `Entity, BlockPos, Block`

- [x] Activate

当方块被鼠标鼠标右键点击时trigger。

Event Fields:  `Entity, BlockPos, Block`

- [x] NeighborChange

当邻近方块状态变更时trigger。

Event Fields:  `ThisBlock, ThisBlockPos, Entity, BlockPos, OldBlock, NewBlock, BlockChangeCause`

- [x] Change

当方块被被变更时通知。

Event Fields:  `Entity, BlockPos, OldBlock, NewBlock, BlockChangeCause`

- [x] Place

当方块被实际放置时通知`NewBlock`。

Event Fields:  `Entity, BlockPos, OldBlock, NewBlock, BlockChangeCause`

- [x] Replace

当方块被实际取代时通知`OldBlock`。

Event Fields:  `Entity, BlockPos, OldBlock, NewBlock, BlockChangeCause`

- [x] Destory

当方块被摧毁为`Air`时通知被摧毁的`Block`。

Event Fields:  `Entity, BlockPos, Block, BlockChangeCause`

- ~~RandomTick~~

这个其实非常需要具体设计一下

提议：
在固定的Interval之间，随机在此interval内某一个tick触发。
例如下面的interval是10tick，每10tick之中必然触发一次，期间每个tick的触发最终应该是平均分布。
| .x........ | ......x... | .........x | ..x....... |

_讨论：是否在只有调用特定`destroy`函数时使用，单纯的`setBlockToAir`不触发?_

**Comment by mouse0w0** [comment]
Should we rename click and activate behaviors? Click behaviors maybe meaning left, right or middle click.
