### ISSUE TITLE
More GUI components

### ISSUE THREAD

**Issue by mouse0w0** [UnknownDomainGames/PanguEngine#34]
Sort by priority:
- [x] ItemView
- [x] ToggleButton
- [x] CheckBox
- [x] Slider
- [x] ScrollBar
- [x] ScrollPane
- [x] ListView

**Comment by cvrunmin** [comment]
what is the difference between `ComboBox` and `ChoiceBox`?

**Comment by mouse0w0** [comment]
> what is the difference between `ComboBox` and `ChoiceBox`?

Why not to see how JavaFX implements `ComboBox` and `ChoiceBox`.

`ChoiceBox` only can select limited items. But `ComboBox` can also type in new items.

**Comment by cvrunmin** [comment]
notes on recent (16:13, 2/10/2019) change on this issue:
ScrollBar is assumed done as it is similar to Slider. Anyone separating these two is welcomed.
