### ISSUE TITLE
客户端与专用服务端之间方块ID同步错误

### ISSUE THREAD

**Issue by xtexx** [UnknownDomainGames/PanguEngine#94]
测试时，草方块被渲染为玻璃，泥土被渲染成草方块，玻璃被渲染为草方块

**Comment by xtexx** [comment]
Note：确认是BlockState的ID同步问题，BlockID同步正常但是BlockStateID仍不一致。

**Comment by mouse0w0** [comment]
为啥会同步BlockID，或者说为啥Block有ID

**Comment by xtexx** [comment]
> 为啥会同步BlockID，或者说为啥Block有ID

Block是SynchronizableIdRegistry啊，数字ID啊，SynchronizableIdRegistry#L37

**Comment by xtexx** [comment]
也许我们需要单独同步BlockState的ID而不是依靠StateIncludedRegistry.reconstructStateId？

**Comment by mouse0w0** [comment]
@cvrunmin 如果要修复的话，Block不应该有ID。
