### ISSUE TITLE
[Bug/Build] Graphics dependency leaking to dedicated server

### ISSUE THREAD

**Issue by xtexx** [UnknownDomainGames/PanguEngine#97]
Modules `joml`, `graphics`, `graphics3d` and `gui` leaked to `server`.

These modules found in the distrobutions that built by `:server:build`. There are graphics modules and should not included in `server`.(Note: LWJGL dependencies were not found in `server`)

`server` depends on `common` and `common` depends on `game-engine`.

`game-engine` depends on `gui` and `graphics3d`, `gui` depends on `graphics`, `graphics` depends on `joml`.

**Comment by mouse0w0** [comment]
`joml` isn't a module and it doesn't contain any graphic operations.

**Comment by mouse0w0** [comment]
Duplicate of #96
